// Origon UI token build pipeline.
// Reads tokens/source/*.json (DTCG format) and emits language-specific outputs
// for React (TypeScript + CSS variables), Flutter (Dart), and Swift (SwiftUI).
//
// Not using Style Dictionary yet — a lightweight custom generator keeps the
// pipeline transparent while we only have primitive/literal tokens. Swap in
// Style Dictionary once we introduce token references (semantic layer).

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SOURCE_DIR = path.join(__dirname, 'source');
const ROOT = path.dirname(__dirname);

const BANNER = `// GENERATED by tokens/build.config.mjs. Do not edit by hand.\n// Regenerate with: pnpm build:tokens\n`;

// Default build: Kripto brand, Dark theme. Additional brands/themes are emitted
// as separate variant files (see emitVariants below).
const DEFAULT_BRAND = 'kripto';
const DEFAULT_THEME = 'dark';

// Files that are always merged into the primary token tree.
const CORE_FILES = ['colors.json', 'typography.json', 'sizes.json'];

// -----------------------------------------------------------------------------
// Load and merge DTCG source files for a given brand × theme combination.
// -----------------------------------------------------------------------------
function loadTokens(brand = DEFAULT_BRAND, theme = DEFAULT_THEME) {
  const files = [
    ...CORE_FILES,
    `theme.${theme}.json`,
    `semantic.${brand}-${theme}.json`,
  ];
  const merged = {};
  for (const file of files) {
    const p = path.join(SOURCE_DIR, file);
    if (!existsSync(p)) continue;
    deepMerge(merged, JSON.parse(readFileSync(p, 'utf8')));
  }
  return merged;
}

function deepMerge(target, source) {
  for (const [key, value] of Object.entries(source)) {
    if (key.startsWith('$')) continue;
    if (value && typeof value === 'object' && !Array.isArray(value) && !('$value' in value)) {
      target[key] = target[key] ?? {};
      deepMerge(target[key], value);
    } else {
      target[key] = value;
    }
  }
}

function walk(node, visit, pathParts = []) {
  if (!node || typeof node !== 'object') return;
  if ('$value' in node) {
    visit(pathParts, node);
    return;
  }
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith('$')) continue;
    walk(child, visit, [...pathParts, key]);
  }
}

// -----------------------------------------------------------------------------
// React (TypeScript + CSS variables)
// -----------------------------------------------------------------------------
function emitReact(tokens) {
  const outDir = path.join(ROOT, 'packages/tokens-react/src/generated');
  mkdirSync(outDir, { recursive: true });
  const cssLines = [':root {'];
  const exports = [];

  // Colors
  if (tokens.color) {
    const tree = extractLeafValues(tokens.color);
    writeFileSync(
      path.join(outDir, 'colors.ts'),
      BANNER +
        `export const colors = ${serializeJs(tree)} as const;\n\nexport type Colors = typeof colors;\nexport type ColorStep = 50 | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900;\n`,
    );
    exports.push("export * from './colors';");
    walk(tokens.color, (parts, node) => {
      cssLines.push(`  --color-${['', ...parts].filter(Boolean).map(kebab).join('-')}: ${node.$value};`);
    });
  }

  // Spacing
  if (tokens.spacing) {
    const flat = flattenDimensions(tokens.spacing);
    writeFileSync(
      path.join(outDir, 'spacing.ts'),
      BANNER + `export const spacing = ${serializeJs(flat, { valueTransform: (v) => `${v}` })} as const;\n`,
    );
    exports.push("export * from './spacing';");
    for (const [k, v] of Object.entries(flat)) {
      cssLines.push(`  --spacing-${kebab(k)}: ${v}px;`);
    }
  }

  // Radius
  if (tokens.radius) {
    const flat = flattenDimensions(tokens.radius);
    writeFileSync(
      path.join(outDir, 'radius.ts'),
      BANNER + `export const radius = ${serializeJs(flat)} as const;\n`,
    );
    exports.push("export * from './radius';");
    for (const [k, v] of Object.entries(flat)) {
      cssLines.push(`  --radius-${kebab(k)}: ${v}px;`);
    }
  }

  // Typography
  if (tokens.text || tokens.font) {
    const font = tokens.font ? extractLeafValues(tokens.font) : {};
    const text = tokens.text ? extractLeafValues(tokens.text) : {};
    const body = `${BANNER}export const font = ${serializeJs(font)} as const;\n\nexport const text = ${serializeJs(text)} as const;\n`;
    writeFileSync(path.join(outDir, 'typography.ts'), body);
    exports.push("export * from './typography';");

    if (font.family) {
      for (const [k, v] of Object.entries(font.family)) {
        cssLines.push(`  --font-family-${kebab(k)}: ${JSON.stringify(v)};`);
      }
    }
    if (font.weight) {
      for (const [k, v] of Object.entries(font.weight)) {
        cssLines.push(`  --font-weight-${kebab(k)}: ${v};`);
      }
    }
    for (const [scale, dims] of Object.entries(text)) {
      for (const [dimKey, val] of Object.entries(dims)) {
        cssLines.push(`  --text-${kebab(scale)}-${kebab(dimKey)}: ${val}${dimKey.endsWith('Size') || dimKey.endsWith('Height') ? 'px' : ''};`);
      }
    }
  }

  // Semantic colors
  if (tokens.semantic) {
    const tree = extractLeafValues(tokens.semantic);
    writeFileSync(
      path.join(outDir, 'semantic.ts'),
      BANNER + `export const semantic = ${serializeJs(tree)} as const;\n`,
    );
    exports.push("export * from './semantic';");
    walk(tokens.semantic, (parts, node) => {
      cssLines.push(`  --semantic-${parts.map(kebab).join('-')}: ${node.$value};`);
    });
  }

  // Sizes
  if (tokens.size) {
    const flat = flattenDimensions(tokens.size);
    writeFileSync(
      path.join(outDir, 'sizes.ts'),
      BANNER + `export const size = ${serializeJs(flat)} as const;\n`,
    );
    exports.push("export * from './sizes';");
    for (const [k, v] of Object.entries(flat)) {
      cssLines.push(`  --size-${kebab(k)}: ${v}px;`);
    }
  }

  // Width / Height (from Themes)
  if (tokens.width) {
    const flat = flattenDimensions(tokens.width);
    writeFileSync(
      path.join(outDir, 'width.ts'),
      BANNER + `export const width = ${serializeJs(flat)} as const;\n`,
    );
    exports.push("export * from './width';");
    for (const [k, v] of Object.entries(flat)) cssLines.push(`  --width-${kebab(k)}: ${v}px;`);
  }
  if (tokens.height) {
    const flat = flattenDimensions(tokens.height);
    writeFileSync(
      path.join(outDir, 'height.ts'),
      BANNER + `export const height = ${serializeJs(flat)} as const;\n`,
    );
    exports.push("export * from './height';");
    for (const [k, v] of Object.entries(flat)) cssLines.push(`  --height-${kebab(k)}: ${v}px;`);
  }

  // Blur (dimensions)
  if (tokens.blur) {
    const flat = flattenDimensions(tokens.blur);
    writeFileSync(
      path.join(outDir, 'blur.ts'),
      BANNER + `export const blur = ${serializeJs(flat)} as const;\n`,
    );
    exports.push("export * from './blur';");
    for (const [k, v] of Object.entries(flat)) cssLines.push(`  --blur-${kebab(k)}: ${v}px;`);
  }

  // Shadow (composite — offsetX, offsetY, blur, spread, color)
  if (tokens.shadow) {
    const shadows = extractLeafValues(tokens.shadow); // e.g. { xl: { offsetX, offsetY, blur, spread, color } }
    // Emit as pre-baked CSS box-shadow strings + TS object with the shorthand.
    const cssShadows = {};
    for (const [key, parts] of Object.entries(shadows)) {
      const s = `${parts.offsetX ?? 0}px ${parts.offsetY ?? 0}px ${parts.blur ?? 0}px ${parts.spread ?? 0}px ${parts.color ?? 'rgba(0,0,0,0)'}`;
      cssShadows[key] = s;
      cssLines.push(`  --shadow-${kebab(key)}: ${s};`);
    }
    writeFileSync(
      path.join(outDir, 'shadow.ts'),
      BANNER + `export const shadow = ${serializeJs(cssShadows)} as const;\n\nexport const shadowParts = ${serializeJs(shadows)} as const;\n`,
    );
    exports.push("export * from './shadow';");
  }

  cssLines.push('}\n');
  writeFileSync(path.join(outDir, 'tokens.css'), BANNER + cssLines.join('\n'));
  // Preserve the legacy import path used by @origon/tokens-react/css.
  writeFileSync(path.join(outDir, 'colors.css'), BANNER + cssLines.join('\n'));

  writeFileSync(path.join(outDir, 'index.ts'), BANNER + exports.join('\n') + '\n');

  return { files: readdirSync(outDir), leaves: countAllLeaves(tokens) };
}

// -----------------------------------------------------------------------------
// Flutter
// -----------------------------------------------------------------------------
function emitFlutter(tokens) {
  const outDir = path.join(ROOT, 'packages/tokens-flutter/lib/generated');
  mkdirSync(outDir, { recursive: true });
  const emittedFiles = [];

  // Colors — keeps existing shape.
  if (tokens.color) {
    const lines = [
      BANNER,
      "import 'package:flutter/painting.dart';",
      '',
      '/// Origon UI primitive + brand color tokens.',
      'class OrigonColors {',
      '  OrigonColors._();',
      '',
    ];
    const swatches = [];
    for (const [category, children] of Object.entries(tokens.color)) {
      if (isSwatch(children)) {
        swatches.push({ name: category, children });
      } else if (isLeaf(children)) {
        lines.push(`  static const Color ${category} = ${flutterColor(children.$value)};`);
      } else {
        for (const [sub, subChildren] of Object.entries(children)) {
          if (isSwatch(subChildren)) {
            swatches.push({ name: `${category}${cap(sub)}`, children: subChildren });
          } else if (isLeaf(subChildren)) {
            lines.push(`  static const Color ${sub} = ${flutterColor(subChildren.$value)};`);
          }
        }
      }
    }
    lines.push('');
    for (const { name, children } of swatches) {
      lines.push(`  static const OrigonSwatch ${name} = OrigonSwatch(`);
      lines.push(
        '    ' +
          [50, 100, 200, 300, 400, 500, 600, 700, 800, 900]
            .map((s) => `s${s}: ${flutterColor(children[String(s)].$value)}`)
            .join(', '),
      );
      lines.push('  );');
    }
    lines.push('}');
    lines.push('');
    lines.push('class OrigonSwatch {');
    lines.push('  final Color s50, s100, s200, s300, s400, s500, s600, s700, s800, s900;');
    lines.push('');
    lines.push('  const OrigonSwatch({');
    lines.push('    required this.s50, required this.s100, required this.s200,');
    lines.push('    required this.s300, required this.s400, required this.s500,');
    lines.push('    required this.s600, required this.s700, required this.s800,');
    lines.push('    required this.s900,');
    lines.push('  });');
    lines.push('');
    lines.push('  Color operator [](int step) {');
    lines.push('    switch (step) {');
    for (const s of [50, 100, 200, 300, 400, 500, 600, 700, 800, 900]) {
      lines.push(`      case ${s}:  return s${s};`);
    }
    lines.push("      default: throw ArgumentError('Step must be 50 or 100..900, got: \\$step');");
    lines.push('    }');
    lines.push('  }');
    lines.push('}');
    lines.push('');
    writeFileSync(path.join(outDir, 'origon_colors.dart'), lines.join('\n'));
    emittedFiles.push('origon_colors.dart');
  }

  if (tokens.spacing) {
    emittedFiles.push(
      emitDartDoubles(outDir, 'origon_spacing.dart', 'OrigonSpacing', flattenDimensions(tokens.spacing)),
    );
  }
  if (tokens.radius) {
    emittedFiles.push(
      emitDartDoubles(outDir, 'origon_radius.dart', 'OrigonRadius', flattenDimensions(tokens.radius)),
    );
  }
  if (tokens.font || tokens.text) {
    emittedFiles.push(emitDartTypography(outDir, tokens));
  }
  if (tokens.semantic) {
    emittedFiles.push(emitDartSemantic(outDir, tokens.semantic));
  }
  if (tokens.size) {
    emittedFiles.push(
      emitDartDoubles(outDir, 'origon_size.dart', 'OrigonSize', flattenDimensions(tokens.size)),
    );
  }
  if (tokens.width) {
    emittedFiles.push(
      emitDartDoubles(outDir, 'origon_width.dart', 'OrigonWidth', flattenDimensions(tokens.width)),
    );
  }
  if (tokens.height) {
    emittedFiles.push(
      emitDartDoubles(outDir, 'origon_height.dart', 'OrigonHeight', flattenDimensions(tokens.height)),
    );
  }
  if (tokens.blur) {
    emittedFiles.push(
      emitDartDoubles(outDir, 'origon_blur.dart', 'OrigonBlur', flattenDimensions(tokens.blur)),
    );
  }
  if (tokens.shadow) {
    emittedFiles.push(emitDartShadow(outDir, tokens.shadow));
  }

  return { files: emittedFiles, leaves: countAllLeaves(tokens) };
}

function emitDartShadow(outDir, shadow) {
  const shadows = extractLeafValues(shadow);
  const lines = [
    BANNER,
    "import 'package:flutter/painting.dart';",
    '',
    '/// Origon UI shadow tokens (Flutter BoxShadow parts).',
    'class OrigonShadow {',
    '  OrigonShadow._();',
    '',
  ];
  for (const [key, parts] of Object.entries(shadows)) {
    const dartKey = /^[a-zA-Z_]/.test(key) ? key : `d${key}`;
    const color = String(parts.color ?? '#0000001a').replace('#', '').toUpperCase();
    // Parse 6/8-char hex → ARGB (default alpha ff if 6 chars).
    const hex = color.length === 8
      ? color.slice(6, 8) + color.slice(0, 6)
      : 'FF' + color;
    lines.push(`  static const BoxShadow ${dartKey} = BoxShadow(`);
    lines.push(`    color: Color(0x${hex}),`);
    lines.push(`    offset: Offset(${parts.offsetX ?? 0}.0, ${parts.offsetY ?? 0}.0),`);
    lines.push(`    blurRadius: ${parts.blur ?? 0}.0,`);
    lines.push(`    spreadRadius: ${parts.spread ?? 0}.0,`);
    lines.push('  );');
  }
  lines.push('}', '');
  writeFileSync(path.join(outDir, 'origon_shadow.dart'), lines.join('\n'));
  return 'origon_shadow.dart';
}

function emitDartSemantic(outDir, semantic) {
  const lines = [
    BANNER,
    "import 'package:flutter/painting.dart';",
    '',
    '/// Origon UI semantic color tokens — reference these in product code, not the primitives.',
    'class OrigonSemantic {',
    '  OrigonSemantic._();',
    '',
  ];
  for (const [group, children] of Object.entries(semantic)) {
    const groupClass = cap(group);
    lines.push(`  static const _Origon${groupClass} ${group} = _Origon${groupClass}();`);
  }
  lines.push('}');
  lines.push('');
  for (const [group, children] of Object.entries(semantic)) {
    const groupClass = cap(group);
    lines.push(`class _Origon${groupClass} {`);
    lines.push(`  const _Origon${groupClass}();`);
    for (const [k, v] of Object.entries(children)) {
      if (isLeaf(v)) {
        lines.push(`  Color get ${dartId(k)} => ${flutterColor(v.$value)};`);
      }
    }
    lines.push('}');
    lines.push('');
  }
  writeFileSync(path.join(outDir, 'origon_semantic.dart'), lines.join('\n'));
  return 'origon_semantic.dart';
}

function emitDartDoubles(outDir, filename, className, entries) {
  const lines = [BANNER, '/// Origon UI dimension tokens.', `class ${className} {`, `  ${className}._();`, ''];
  for (const [k, v] of Object.entries(entries)) {
    lines.push(`  static const double ${dartId(k)} = ${v}.0;`);
  }
  lines.push('}', '');
  writeFileSync(path.join(outDir, filename), lines.join('\n'));
  return filename;
}

function emitDartTypography(outDir, tokens) {
  const font = tokens.font ? extractLeafValues(tokens.font) : {};
  const text = tokens.text ? extractLeafValues(tokens.text) : {};
  const lines = [
    BANNER,
    "import 'package:flutter/painting.dart';",
    '',
    '/// Origon UI typography tokens.',
    'class OrigonFont {',
    '  OrigonFont._();',
    '',
  ];
  for (const [k, v] of Object.entries(font.family ?? {})) {
    lines.push(`  static const String ${dartId(k)} = ${JSON.stringify(v)};`);
  }
  lines.push('');
  for (const [k, v] of Object.entries(font.weight ?? {})) {
    lines.push(`  static const FontWeight ${dartId(k)} = FontWeight.w${v};`);
  }
  lines.push('}');
  lines.push('');
  lines.push('class OrigonTextStyles {');
  lines.push('  OrigonTextStyles._();');
  lines.push('');
  for (const [scale, dims] of Object.entries(text)) {
    const size = dims.fontSize;
    const lh = dims.lineHeight;
    lines.push(
      `  static const TextStyle ${dartId(scale)} = TextStyle(fontSize: ${size}.0, height: ${(lh / size).toFixed(4)});`,
    );
  }
  lines.push('}', '');
  writeFileSync(path.join(outDir, 'origon_typography.dart'), lines.join('\n'));
  return 'origon_typography.dart';
}

// -----------------------------------------------------------------------------
// Swift (SwiftUI)
// -----------------------------------------------------------------------------
function emitSwift(tokens) {
  const outDir = path.join(ROOT, 'packages/tokens-swift/Sources/OrigonTokens/generated');
  mkdirSync(outDir, { recursive: true });
  const emittedFiles = [];

  if (tokens.color) {
    const lines = [
      BANNER,
      'import SwiftUI',
      '',
      '/// Origon UI primitive + brand color tokens.',
      'public enum OrigonColors {',
    ];
    const swatches = [];
    for (const [category, children] of Object.entries(tokens.color)) {
      if (isSwatch(children)) {
        swatches.push({ name: category, children });
      } else if (isLeaf(children)) {
        const hex = children.$value.replace('#', '').toUpperCase();
        lines.push(`    public static let ${category} = Color(hex: 0x${hex})`);
      } else {
        for (const [sub, subChildren] of Object.entries(children)) {
          if (isSwatch(subChildren)) {
            swatches.push({ name: `${category}${cap(sub)}`, children: subChildren });
          } else if (isLeaf(subChildren)) {
            const hex = subChildren.$value.replace('#', '').toUpperCase();
            lines.push(`    public static let ${sub} = Color(hex: 0x${hex})`);
          }
        }
      }
    }
    lines.push('');
    for (const { name, children } of swatches) {
      lines.push(`    public static let ${name} = Swatch(`);
      lines.push(
        '        ' +
          [50, 100, 200, 300, 400, 500, 600, 700, 800, 900]
            .map((s) => `s${s}: 0x${children[String(s)].$value.replace('#', '').toUpperCase()}`)
            .join(', '),
      );
      lines.push('    )');
    }
    lines.push('');
    lines.push('    public struct Swatch {');
    lines.push('        public let s50, s100, s200, s300, s400, s500, s600, s700, s800, s900: Color');
    lines.push('');
    lines.push('        public init(');
    lines.push('            s50: UInt32, s100: UInt32, s200: UInt32, s300: UInt32, s400: UInt32,');
    lines.push('            s500: UInt32, s600: UInt32, s700: UInt32, s800: UInt32, s900: UInt32');
    lines.push('        ) {');
    for (const s of [50, 100, 200, 300, 400, 500, 600, 700, 800, 900]) {
      lines.push(`            self.s${s} = Color(hex: s${s})`);
    }
    lines.push('        }');
    lines.push('');
    lines.push('        public subscript(step: Int) -> Color {');
    lines.push('            switch step {');
    for (const s of [50, 100, 200, 300, 400, 500, 600, 700, 800, 900]) {
      lines.push(`            case ${s}:  return s${s}`);
    }
    lines.push('            default: fatalError("OrigonColors.Swatch step must be 50 or 100..900, got: \\(step)")');
    lines.push('            }');
    lines.push('        }');
    lines.push('    }');
    lines.push('}');
    lines.push('');
    lines.push('public extension Color {');
    lines.push('    init(hex: UInt32) {');
    lines.push('        let r = Double((hex >> 16) & 0xFF) / 255.0');
    lines.push('        let g = Double((hex >> 8) & 0xFF) / 255.0');
    lines.push('        let b = Double(hex & 0xFF) / 255.0');
    lines.push('        self.init(.sRGB, red: r, green: g, blue: b, opacity: 1.0)');
    lines.push('    }');
    lines.push('}');
    lines.push('');
    writeFileSync(path.join(outDir, 'OrigonColors.swift'), lines.join('\n'));
    emittedFiles.push('OrigonColors.swift');
  }

  if (tokens.spacing) {
    emittedFiles.push(emitSwiftDoubles(outDir, 'OrigonSpacing.swift', 'OrigonSpacing', flattenDimensions(tokens.spacing)));
  }
  if (tokens.radius) {
    emittedFiles.push(emitSwiftDoubles(outDir, 'OrigonRadius.swift', 'OrigonRadius', flattenDimensions(tokens.radius)));
  }
  if (tokens.font || tokens.text) {
    emittedFiles.push(emitSwiftTypography(outDir, tokens));
  }
  if (tokens.semantic) {
    emittedFiles.push(emitSwiftSemantic(outDir, tokens.semantic));
  }
  if (tokens.size) {
    emittedFiles.push(emitSwiftDoubles(outDir, 'OrigonSize.swift', 'OrigonSize', flattenDimensions(tokens.size)));
  }
  if (tokens.width) {
    emittedFiles.push(emitSwiftDoubles(outDir, 'OrigonWidth.swift', 'OrigonWidth', flattenDimensions(tokens.width)));
  }
  if (tokens.height) {
    emittedFiles.push(emitSwiftDoubles(outDir, 'OrigonHeight.swift', 'OrigonHeight', flattenDimensions(tokens.height)));
  }
  if (tokens.blur) {
    emittedFiles.push(emitSwiftDoubles(outDir, 'OrigonBlur.swift', 'OrigonBlur', flattenDimensions(tokens.blur)));
  }
  if (tokens.shadow) {
    emittedFiles.push(emitSwiftShadow(outDir, tokens.shadow));
  }

  return { files: emittedFiles, leaves: countAllLeaves(tokens) };
}

function emitSwiftShadow(outDir, shadow) {
  const shadows = extractLeafValues(shadow);
  const lines = [
    BANNER,
    'import SwiftUI',
    '',
    '/// Origon UI shadow tokens as reusable ViewModifiers.',
    '/// Usage:  MyView().origonShadow(.xl)',
    '',
    'public struct OrigonShadowSpec {',
    '    public let color: Color',
    '    public let offsetX: CGFloat',
    '    public let offsetY: CGFloat',
    '    public let radius: CGFloat',
    '    public let spread: CGFloat',
    '}',
    '',
    'public enum OrigonShadow: String, CaseIterable {',
  ];
  for (const key of Object.keys(shadows)) {
    lines.push(`    case ${swiftId(key)}`);
  }
  lines.push('');
  lines.push('    public var spec: OrigonShadowSpec {');
  lines.push('        switch self {');
  for (const [key, parts] of Object.entries(shadows)) {
    const hex = String(parts.color ?? '#0000001a').replace('#', '');
    const rgb = hex.length >= 6 ? hex.slice(0, 6) : '000000';
    const alpha = hex.length === 8 ? parseInt(hex.slice(6, 8), 16) / 255 : 1;
    lines.push(`        case .${swiftId(key)}: return OrigonShadowSpec(color: Color(hex: 0x${rgb.toUpperCase()}).opacity(${alpha.toFixed(3)}), offsetX: ${parts.offsetX ?? 0}, offsetY: ${parts.offsetY ?? 0}, radius: ${parts.blur ?? 0}, spread: ${parts.spread ?? 0})`);
  }
  lines.push('        }');
  lines.push('    }');
  lines.push('}');
  lines.push('');
  lines.push('public extension View {');
  lines.push('    /// Applies an Origon UI shadow token.');
  lines.push('    func origonShadow(_ shadow: OrigonShadow) -> some View {');
  lines.push('        let s = shadow.spec');
  lines.push('        return self.shadow(color: s.color, radius: s.radius, x: s.offsetX, y: s.offsetY)');
  lines.push('    }');
  lines.push('}');
  lines.push('');
  writeFileSync(path.join(outDir, 'OrigonShadow.swift'), lines.join('\n'));
  return 'OrigonShadow.swift';
}

function emitSwiftSemantic(outDir, semantic) {
  const lines = [
    BANNER,
    'import SwiftUI',
    '',
    '/// Origon UI semantic color tokens — reference these in product code, not the primitives.',
    'public enum OrigonSemantic {',
  ];
  for (const [group, children] of Object.entries(semantic)) {
    lines.push(`    public enum ${cap(group)} {`);
    for (const [k, v] of Object.entries(children)) {
      if (isLeaf(v)) {
        const hex = v.$value.replace('#', '').toUpperCase();
        lines.push(`        public static let ${swiftId(k)} = Color(hex: 0x${hex})`);
      }
    }
    lines.push('    }');
  }
  lines.push('}', '');
  writeFileSync(path.join(outDir, 'OrigonSemantic.swift'), lines.join('\n'));
  return 'OrigonSemantic.swift';
}

function emitSwiftDoubles(outDir, filename, enumName, entries) {
  const lines = [BANNER, 'import CoreGraphics', '', `public enum ${enumName} {`];
  for (const [k, v] of Object.entries(entries)) {
    lines.push(`    public static let ${swiftId(k)}: CGFloat = ${v}`);
  }
  lines.push('}', '');
  writeFileSync(path.join(outDir, filename), lines.join('\n'));
  return filename;
}

function emitSwiftTypography(outDir, tokens) {
  const font = tokens.font ? extractLeafValues(tokens.font) : {};
  const text = tokens.text ? extractLeafValues(tokens.text) : {};
  const lines = [BANNER, 'import SwiftUI', '', 'public enum OrigonFont {'];
  for (const [k, v] of Object.entries(font.family ?? {})) {
    lines.push(`    public static let ${swiftId(k)} = ${JSON.stringify(v)}`);
  }
  lines.push('');
  for (const [k, v] of Object.entries(font.weight ?? {})) {
    lines.push(`    public static let ${swiftId(k)} = Font.Weight.${swiftWeight(v)}`);
  }
  lines.push('}');
  lines.push('');
  lines.push('public enum OrigonTextStyles {');
  for (const [scale, dims] of Object.entries(text)) {
    lines.push(
      `    public static let ${swiftId(scale)} = Font.system(size: ${dims.fontSize}) // lineHeight: ${dims.lineHeight}`,
    );
  }
  lines.push('}', '');
  writeFileSync(path.join(outDir, 'OrigonTypography.swift'), lines.join('\n'));
  return 'OrigonTypography.swift';
}

function swiftWeight(v) {
  return { 100: 'ultraLight', 200: 'thin', 300: 'light', 400: 'regular', 500: 'medium', 600: 'semibold', 700: 'bold', 800: 'heavy', 900: 'black' }[v] ?? 'regular';
}

// -----------------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------------
function isLeaf(node) {
  return node && typeof node === 'object' && '$value' in node;
}
function isSwatch(node) {
  if (!node || typeof node !== 'object') return false;
  const keys = Object.keys(node).filter((k) => !k.startsWith('$'));
  return keys.length > 0 && keys.every((k) => /^\d+$/.test(k) && isLeaf(node[k]));
}
function extractLeafValues(node) {
  if (isLeaf(node)) return node.$value;
  const out = {};
  for (const [k, v] of Object.entries(node)) {
    if (k.startsWith('$')) continue;
    out[k] = extractLeafValues(v);
  }
  return out;
}
function flattenDimensions(node, prefix = '', acc = {}) {
  for (const [k, v] of Object.entries(node)) {
    if (k.startsWith('$')) continue;
    if (isLeaf(v)) acc[prefix + k] = v.$value;
    else flattenDimensions(v, prefix + k + '_', acc);
  }
  return acc;
}
function serializeJs(value, opts = {}, indent = 0) {
  if (typeof value === 'string') return JSON.stringify(value);
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (Array.isArray(value)) {
    return '[' + value.map((v) => serializeJs(v, opts, indent + 1)).join(', ') + ']';
  }
  const pad = '  '.repeat(indent + 1);
  const closePad = '  '.repeat(indent);
  const entries = Object.entries(value).map(([k, v]) => {
    const key = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k) ? k : JSON.stringify(k);
    return `${pad}${key}: ${serializeJs(v, opts, indent + 1)}`;
  });
  return `{\n${entries.join(',\n')},\n${closePad}}`;
}
function flutterColor(hex) {
  return `Color(0xFF${hex.replace('#', '').toUpperCase()})`;
}
function kebab(s) {
  return s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}
function cap(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
function dartId(s) {
  // Dart identifiers can't start with a digit.
  return /^[a-zA-Z_]/.test(s) ? s : `d${s}`;
}
function swiftId(s) {
  return /^[a-zA-Z_]/.test(s) ? s : `d${s}`;
}
function countAllLeaves(tokens) {
  let n = 0;
  walk(tokens, () => n++);
  return n;
}

// -----------------------------------------------------------------------------
// Multi-brand / multi-theme variants
// -----------------------------------------------------------------------------
const BRANDS = ['kripto', 'hisse', 'global'];
const THEMES = ['dark', 'light'];

function emitFlutterThemes() {
  const outDir = path.join(ROOT, 'packages/tokens-flutter/lib/generated');
  mkdirSync(outDir, { recursive: true });

  // Discover semantic structure from the default mode. All 6 modes share the
  // same shape (only values differ).
  const seed = loadTokens(DEFAULT_BRAND, DEFAULT_THEME).semantic ?? {};
  const groupNames = Object.keys(seed);

  // Group -> ordered list of leaf field names.
  const groupFields = {};
  for (const g of groupNames) {
    const fields = [];
    for (const [k, v] of Object.entries(seed[g])) {
      if (isLeaf(v)) fields.push(k);
    }
    groupFields[g] = fields;
  }

  const lines = [
    BANNER,
    "import 'package:flutter/painting.dart';",
    '',
    '/// Origon UI semantic color tokens across all 6 brand × theme modes.',
    '/// Access via `OrigonTheme.of(context).semantic.button.primary`.',
    '',
  ];

  // Emit one class per semantic group.
  for (const g of groupNames) {
    const cls = `OrigonSemantic${cap(g)}`;
    lines.push(`class ${cls} {`);
    for (const f of groupFields[g]) lines.push(`  final Color ${dartId(f)};`);
    lines.push('');
    lines.push(`  const ${cls}({`);
    for (const f of groupFields[g]) lines.push(`    required this.${dartId(f)},`);
    lines.push('  });');
    lines.push('}');
    lines.push('');
  }

  // Aggregate semantic root class.
  lines.push('class OrigonSemanticColors {');
  for (const g of groupNames) lines.push(`  final OrigonSemantic${cap(g)} ${g};`);
  lines.push('');
  lines.push('  const OrigonSemanticColors({');
  for (const g of groupNames) lines.push(`    required this.${g},`);
  lines.push('  });');
  lines.push('}');
  lines.push('');

  // ThemeData wrapper.
  lines.push('enum OrigonBrand { kripto, hisse, global }');
  lines.push('enum OrigonThemeMode { dark, light }');
  lines.push('');
  lines.push('class OrigonThemeData {');
  lines.push('  final OrigonBrand brand;');
  lines.push('  final OrigonThemeMode mode;');
  lines.push('  final OrigonSemanticColors semantic;');
  lines.push('  const OrigonThemeData({required this.brand, required this.mode, required this.semantic});');
  lines.push('}');
  lines.push('');

  // Emit constant OrigonSemanticColors for each brand×theme.
  for (const brand of BRANDS) {
    for (const theme of THEMES) {
      const t = loadTokens(brand, theme);
      const s = t.semantic ?? {};
      lines.push(`const OrigonSemanticColors _${brand}${cap(theme)}Semantic = OrigonSemanticColors(`);
      for (const g of groupNames) {
        lines.push(`  ${g}: OrigonSemantic${cap(g)}(`);
        for (const f of groupFields[g]) {
          const val = s[g]?.[f]?.$value;
          const color = val ? flutterColor(val) : 'Color(0x00000000)';
          lines.push(`    ${dartId(f)}: ${color},`);
        }
        lines.push('  ),');
      }
      lines.push(');');
      lines.push('');
    }
  }

  // Public map keyed by brand×theme.
  lines.push('class OrigonThemes {');
  for (const brand of BRANDS) {
    for (const theme of THEMES) {
      const name = `${brand}${cap(theme)}`;
      lines.push(`  static const OrigonThemeData ${name} = OrigonThemeData(`);
      lines.push(`    brand: OrigonBrand.${brand},`);
      lines.push(`    mode: OrigonThemeMode.${theme},`);
      lines.push(`    semantic: _${brand}${cap(theme)}Semantic,`);
      lines.push('  );');
    }
  }
  lines.push('');
  lines.push('  static OrigonThemeData resolve(OrigonBrand brand, OrigonThemeMode mode) {');
  lines.push('    switch (brand) {');
  for (const brand of BRANDS) {
    lines.push(`      case OrigonBrand.${brand}:`);
    lines.push(`        return mode == OrigonThemeMode.dark ? ${brand}Dark : ${brand}Light;`);
  }
  lines.push('    }');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  writeFileSync(path.join(outDir, 'origon_themes.dart'), lines.join('\n'));

  return { modes: BRANDS.length * THEMES.length, groups: groupNames.length };
}

function emitSwiftThemes() {
  const outDir = path.join(ROOT, 'packages/tokens-swift/Sources/OrigonTokens/generated');
  mkdirSync(outDir, { recursive: true });

  const seed = loadTokens(DEFAULT_BRAND, DEFAULT_THEME).semantic ?? {};
  const groupNames = Object.keys(seed);
  const groupFields = {};
  for (const g of groupNames) {
    groupFields[g] = Object.keys(seed[g]).filter((k) => isLeaf(seed[g][k]));
  }

  const lines = [BANNER, 'import SwiftUI', '', '/// Origon UI semantic color tokens across all 6 brand × theme modes.', ''];

  // Struct per group.
  for (const g of groupNames) {
    lines.push(`public struct OrigonSemantic${cap(g)} {`);
    for (const f of groupFields[g]) lines.push(`    public let ${swiftId(f)}: Color`);
    lines.push('');
    lines.push(`    public init(${groupFields[g].map((f) => `${swiftId(f)}: Color`).join(', ')}) {`);
    for (const f of groupFields[g]) lines.push(`        self.${swiftId(f)} = ${swiftId(f)}`);
    lines.push('    }');
    lines.push('}');
    lines.push('');
  }

  lines.push('public struct OrigonSemanticColors {');
  for (const g of groupNames) lines.push(`    public let ${g}: OrigonSemantic${cap(g)}`);
  lines.push('');
  lines.push(`    public init(${groupNames.map((g) => `${g}: OrigonSemantic${cap(g)}`).join(', ')}) {`);
  for (const g of groupNames) lines.push(`        self.${g} = ${g}`);
  lines.push('    }');
  lines.push('}');
  lines.push('');

  lines.push('public enum OrigonBrand: String, CaseIterable { case kripto, hisse, global }');
  lines.push('public enum OrigonThemeMode: String, CaseIterable { case dark, light }');
  lines.push('');
  lines.push('public struct OrigonThemeData {');
  lines.push('    public let brand: OrigonBrand');
  lines.push('    public let mode: OrigonThemeMode');
  lines.push('    public let semantic: OrigonSemanticColors');
  lines.push('');
  lines.push('    public init(brand: OrigonBrand, mode: OrigonThemeMode, semantic: OrigonSemanticColors) {');
  lines.push('        self.brand = brand; self.mode = mode; self.semantic = semantic');
  lines.push('    }');
  lines.push('}');
  lines.push('');

  // Per-mode constants inside enum.
  lines.push('public enum OrigonThemes {');
  for (const brand of BRANDS) {
    for (const theme of THEMES) {
      const t = loadTokens(brand, theme);
      const s = t.semantic ?? {};
      const name = `${brand}${cap(theme)}`;
      lines.push(`    public static let ${name} = OrigonThemeData(`);
      lines.push(`        brand: .${brand}, mode: .${theme},`);
      lines.push(`        semantic: OrigonSemanticColors(`);
      for (const [gi, g] of groupNames.entries()) {
        const args = groupFields[g].map((f) => {
          const val = s[g]?.[f]?.$value;
          const hex = val ? '0x' + val.replace('#', '').slice(0, 6).toUpperCase() : '0x000000';
          return `${swiftId(f)}: Color(hex: ${hex})`;
        }).join(', ');
        const suffix = gi === groupNames.length - 1 ? '' : ',';
        lines.push(`            ${g}: OrigonSemantic${cap(g)}(${args})${suffix}`);
      }
      lines.push('        )');
      lines.push('    )');
    }
  }
  lines.push('');
  lines.push('    public static func resolve(_ brand: OrigonBrand, _ mode: OrigonThemeMode) -> OrigonThemeData {');
  lines.push('        switch (brand, mode) {');
  for (const brand of BRANDS) {
    for (const theme of THEMES) {
      lines.push(`        case (.${brand}, .${theme}): return ${brand}${cap(theme)}`);
    }
  }
  lines.push('        }');
  lines.push('    }');
  lines.push('}');
  lines.push('');

  writeFileSync(path.join(outDir, 'OrigonThemes.swift'), lines.join('\n'));

  return { modes: BRANDS.length * THEMES.length, groups: groupNames.length };
}

function emitReactThemes() {
  const outDir = path.join(ROOT, 'packages/tokens-react/src/generated/themes');
  mkdirSync(outDir, { recursive: true });

  const cssLines = [BANNER, '/* Scoped tokens for every brand × theme combination.', ' * Apply the appropriate data-* attributes to the root element:', ' *   <html data-brand="kripto" data-theme="dark">                 */', ''];

  const variantsIndex = [];

  for (const brand of BRANDS) {
    for (const theme of THEMES) {
      const t = loadTokens(brand, theme);
      const selector = `[data-brand="${brand}"][data-theme="${theme}"]`;
      const nested = brand === DEFAULT_BRAND && theme === DEFAULT_THEME
        ? [':root, ' + selector]
        : [selector];

      // CSS variables — walk full tree.
      cssLines.push(`${nested.join(', ')} {`);
      if (t.color) walk(t.color, (parts, node) => cssLines.push(`  --color-${['', ...parts].filter(Boolean).map(kebab).join('-')}: ${node.$value};`));
      if (t.semantic) walk(t.semantic, (parts, node) => cssLines.push(`  --semantic-${parts.map(kebab).join('-')}: ${node.$value};`));
      if (t.spacing) {
        for (const [k, v] of Object.entries(flattenDimensions(t.spacing))) cssLines.push(`  --spacing-${kebab(k)}: ${v}px;`);
      }
      if (t.radius) {
        for (const [k, v] of Object.entries(flattenDimensions(t.radius))) cssLines.push(`  --radius-${kebab(k)}: ${v}px;`);
      }
      cssLines.push('}', '');

      // TS variant module — exports resolved values as a nested object.
      const tsBody = [
        BANNER,
        `// Brand: ${brand}, Theme: ${theme}`,
        '',
        `export const tokens = {`,
        `  color: ${t.color ? serializeJs(extractLeafValues(t.color)) : '{}'},`,
        `  semantic: ${t.semantic ? serializeJs(extractLeafValues(t.semantic)) : '{}'},`,
        `  spacing: ${t.spacing ? serializeJs(flattenDimensions(t.spacing)) : '{}'},`,
        `  radius: ${t.radius ? serializeJs(flattenDimensions(t.radius)) : '{}'},`,
        `} as const;`,
        '',
      ].join('\n');
      const variantFile = `${brand}-${theme}.ts`;
      writeFileSync(path.join(outDir, variantFile), tsBody);
      variantsIndex.push({ brand, theme, file: variantFile });
    }
  }

  writeFileSync(path.join(outDir, 'themes.css'), cssLines.join('\n'));

  // Central index — provides types + a `themes` map + a `applyTheme` helper.
  const idxLines = [
    BANNER,
    ...variantsIndex.map(
      ({ brand, theme, file }) => `import { tokens as ${brand}${cap(theme)} } from './${file.replace(/\.ts$/, '')}';`,
    ),
    '',
    `export type Brand = ${BRANDS.map((b) => JSON.stringify(b)).join(' | ')};`,
    `export type Theme = ${THEMES.map((t) => JSON.stringify(t)).join(' | ')};`,
    '',
    'export const themes = {',
    ...variantsIndex.map(({ brand, theme }) => `  '${brand}-${theme}': ${brand}${cap(theme)},`),
    '} as const;',
    '',
    'export type ThemeKey = keyof typeof themes;',
    '',
    'export function getTokens(brand: Brand, theme: Theme) {',
    "  return themes[`${brand}-${theme}` as ThemeKey];",
    '}',
    '',
    '/** Applies a brand/theme by setting data-* attributes on document.documentElement. */',
    'export function applyTheme(brand: Brand, theme: Theme) {',
    "  if (typeof document === 'undefined') return;",
    "  document.documentElement.setAttribute('data-brand', brand);",
    "  document.documentElement.setAttribute('data-theme', theme);",
    '}',
    '',
  ];
  writeFileSync(path.join(outDir, 'index.ts'), idxLines.join('\n'));

  return { variants: variantsIndex.length };
}

// -----------------------------------------------------------------------------
// Entry
// -----------------------------------------------------------------------------
const tokens = loadTokens();
const react = emitReact(tokens);
const flutter = emitFlutter(tokens);
const swift = emitSwift(tokens);
const multi = emitReactThemes();
const flutterMulti = emitFlutterThemes();
const swiftMulti = emitSwiftThemes();

console.log(`Default build: brand=${DEFAULT_BRAND} theme=${DEFAULT_THEME}`);
console.log(`✓ tokens-react   ${react.files.join(', ')} (${react.leaves} tokens)`);
console.log(`✓ tokens-flutter ${flutter.files.join(', ')} (${flutter.leaves} tokens)`);
console.log(`✓ tokens-swift   ${swift.files.join(', ')} (${swift.leaves} tokens)`);
console.log(`✓ tokens-react/themes    ${multi.variants} brand×theme variants (+ themes.css scoped selectors)`);
console.log(`✓ tokens-flutter/themes  ${flutterMulti.modes} modes × ${flutterMulti.groups} semantic groups`);
console.log(`✓ tokens-swift/themes    ${swiftMulti.modes} modes × ${swiftMulti.groups} semantic groups`);
