export default {
  bullet: 'Bullet',
  button: 'Button',
  chart: 'Chart',
  checkbox: 'Checkbox',
  chip: 'Chip',
  drawer: 'Drawer',
  dropdown: 'Dropdown / Combo',
  filter: 'Filter',
  gauge: 'Gauge',
  graph: 'Graph',
  icons: 'Icons + Logos',
  'info-row': 'Info Row',
  input: 'Input',
  keyboard: 'Keyboard',
  loader: 'Loader',
  logos: 'Logos',
  menu: 'Menu',
  'multi-line-input': 'MultiLine Input',
  'notification-badge': 'Notification Badge',
  'progress-stepper': 'Progress Stepper',
  radio: 'Radio',
  'range-slider': 'Range Slider',
  row: 'Row',
  segmented: 'Segmented Control',
  table: 'Table',
  tabs: 'Tabs',
  ticker: 'Ticker',
  toast: 'Toast',
  toggle: 'Toggle',
  tooltip: 'Tooltip',
};
